language: java

sudo: required

notifications:
email: james.hn.sears@gmail.com

env:
  global:
    # travis encrypt COVERALLS_REPO_TOKEN=...
    - secure: "OlJmZFX4lPm0MhSLTqM7V+CtgeMTl4GDD5kpPqXPdCFGSpPT14fAtufXEygZrNyoQ/vGT+GR4vzCGFO2FWsAPY8nPMwZVLF8GhcUezIQmaSekq1dC7i1EY5FqxaO/bxkkGJpbe8wdZqvJpXp5w4Bw4jUOVSqwU6iFUcv6s+VGE8Li74xTJkH4Lg5Gu+sl+gmXZhxmqe7fEGK7g1xo7K3QlUoYblZTEx1+z8a2WWcRDvag+2LbHd0LFhtWXRqu2NwuQVxkZiU2Y2Z9mWuWZ8Lob1Ape7HnapN8UIgzbfrjPPtdJ//c08bNPJSpuw1B3Sml59VAtxubALIwzxwnmnNYTU7Pf//MFLAqcDPSIIOt/SfqppX7SeUM03Xv7ZhxBuzdnyNzTDdVjFEB5tSbcmW4ZlGtBcjd1qNyh+TJ8t3ZoUjLa5OV3EypW9eSTTqpPKdj/qjV+TDpzpjIprRatPaU0p25u+zqczTaxT/3y3CZjU2DDA/c9DJk+7mnLyXYa4z4kcaPiB5ziaIwDYToUrUAbVEWvz7nmJa9qregEgLlIF0KKLwTceWEBMmxtgLKVGnHhMg42I+aGT2T8tBNGEgxUH7lOnEUhmw1Vfdv6eqbC3yXEGB9C3EpovckyoLqeiceMfoDAwBncdkMOiTUw89BWogYN+u8s6IcFLs5y4DLBE="
    # travis encrypt CODACY_PROJECT_TOKEN=...
    - secure: "DGDqvFmJWNM9yjQF53vRa8wIFtLwuIu/f513QxEQGWTdaIxvESertoNBhgq4bIbxVbcF61LDMifgtsYqKOFIfTGF3THREezn5DH1jpeXQPKvZRq9pW1F7/9VTV3jSJXf7rgGX/YJ/01N+gOrOe6ckcvL5Yjtc5YF3lU8A4kBrDRQ2d6o9vpDeu3eb7UURULVrBUgo+9p2AJ7W3Mdvuy4UoZxysBY5JIp5ckNfdLdjEyo31KrKAlzlv2rYpUXi0ujwjrgZVSi7NZADWWA8nuBZosYOVKges6tt0GpPfW5sQjJK0Xx6sp8wBKN//klE+U/LQI9iPrO4VVWqCG+915wPazvQztWuT52pvuboGPAQGrbr4YPh97bPAYdEye6qpVHIopIEp4snjb1FXmytoZXYYz1YyU+B0pB7f0aMeyxKTFVoOqP+IYoCe1WgaK2DxnklutFo4jfmZhlxE0uVl9iwMZ+TXOF13+VagmYNSBtApwXais36K0sl2PUZqbkF0F9u5sKvCMvrINH3AnyyOPLpsDwqS7gVaHdfEe9dJdqF9WvItR/gq3kxgeX0WPQILjm753WdkhvY0n8Di06OVujJ9ZrOAVADSdlGr8blTPwwyCsL4ZYrx5PRs+ceiblmHgtf2KWqeWZuoTzxXzyPDrBuUe0QQdiuPrSbgIVxSgZDkA="

addons:
  sonarcloud:
    organization: "jameshnsears-github"
    token:
      secure: "XwUFX8/52MnV+zTUszl4NPA6/8JcKiAJKS6K1xpXIBB9B/Kmp0BDOQFXEzBukMtu/HMTdJjNpqzMYtu9i9p8Wz3c0Va0/T0qVEDpAeyVhO9RCdP21U6duhAg2Ji9M9HmCo/HYQm4CMb/o2Sm93/TUJ3MXuY7f811XoVg0eQf3p5rI6cHBIKVwpU9OY+/VmeRaUkf5fjYvNWY7FFvtIY+BSsYRdIql9EaerPh2lrQCBkpPIgSYY2MwItu0sZQxCrztL/LRS/5kne5qUBukn2A1DeRyHWPBu/tgk5ORFGgEGenNjLeqwd41k4WUSB/61e3VSpvicVVx0drE398boA65/2zPEuA8HvsdtumF7GdL5ifmoA0pIn02BJ+J/ZwZ7Be+YG6UkUGjUeuUqopxmIcT547M4cdWeA0Xzj+xg7gWvYJNNLO7XqxV+9IaiFv3BNyaUR3kMj7Fn7sIFDTUFxSx3mTDZTnmiI74X+a3jiAmDl0VzVWR7JZUdCMQVZOUs+jeC8Dh5QOpg93vsQ1+iGWNLLxNRKqfEgfg1t/5Xjsa/lhcDjhZ06wO00OyDSi7iUsuETNnr4wkqThmGWSYrUMxAmzRkOg19b2zsh31FHLNMkt3iPRF+6Jh/2IMMWAzGtjQOeAloWOZNLHP8G24MR7JWaL3va9CGVr58WlqC0vvuk="

git:
  depth: false

services:
  - docker

jdk:
  - openjdk10

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

before_script:
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
  - wget https://github.com/codacy/codacy-coverage-reporter/releases/download/4.0.5/codacy-coverage-reporter-4.0.5-assembly.jar

script:
  - docker-compose up -d xqa-db xqa-message-broker xqa-ingest-balancer
  - docker-compose up -d --scale xqa-shard=2
  - mvn clean test
  - mvn checkstyle:check spotbugs:check pmd:pmd

after_success:
  - mvn jacoco:report coveralls:report
  - java -jar codacy-coverage-reporter-4.0.5-assembly.jar report -l Java -r target/site/jacoco/jacoco.xml
  - sonar-scanner
