language: java

sudo: required

notifications:
email: james.hn.sears@gmail.com

services:
  - docker

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_script:
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

script:
  - docker-compose -p "dev" up -d xqa-db
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn clean test

after_success:
  - mvn jacoco:report coveralls:report