language: java

sudo: required

notifications:
email: james.hn.sears@gmail.com

services:
  - docker

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_script:
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

script:
  - docker network create xqa

  - docker volume create xqa-db
  - docker pull jameshnsears/xqa-db
  - docker run -d --net="xqa" --name="xqa-db" -p 5432:5432 jameshnsears/xqa-db

  - mvn clean test
  - mvn package -DskipTests

after_success:
  - mvn jacoco:report coveralls:report
