language: java

sudo: required

notifications:
email: james.hn.sears@gmail.com

env:
  global:
    # travis encrypt COVERALLS_REPO_TOKEN=...
    - secure: "EhMRLMjwGeg85i6hqKqdAhESTf4jG2n0yXKHkGbuuxKu6t0SjTHHvv7An+gaEbES2jWv9xUAaTyCR/eQJFrgi5oAEjyZbumPjX755G6FtXgVP0bbg/gxPJZI7pcqIFh1fKUebLYhtVnbvIjWqL5E1R0+vAcDnB4dww69K4nL+2sYLEDAXvI7hWPeRZZUodbfeureEsmv3+TxbPsKe9NEYLmdnpqhVXZb/efh2mXvu6YBhUe3ghqiKzmXSuJh6q8vErhxxAxlMItuf6r8fvEf0K9wAX10Yg9Rs4QqUpoHMrgnvLbV6P+sJTvZW0iMRwjxpEQW9vKugfqZBLGwC++Q+8FH/xsTLoUGy6rdiwtwQSZHG7bMnlk9W54ZuMZMSO9h+CeGwVl19AGvHhNU1PyUhPQPfo8U2VVG8sn3WlYzKGMxJdS6hi3T9xNMo54Hbyn9XuLdepPkFbSFY/g+Pnz8P6j8nLK81wUfyIpIDe3/o+/Bkyh+AGqbrOPQjNb/r2MV7i7lnxqxdob4ivEnC5Zs5nG4DWzoaT9KY2ZJr/JVcGjF8PnoemtBbq65S8hgHblPZJuw5FmURmhh1KejC4R754X6wwRVUCbL0KoUj/KZnFZWTy8ddXtW1kBmmcfYpal3SIppFKnuM3Yf+nVjrMTbRi65SHqlh8E8GuaOSfH5ZdM="
    # travis encrypt CODACY_PROJECT_TOKEN=...
    - secure: "ZaXmBTFfvX20ipUSUz5ChkGkuh7jLvjpUgV9z+wPCz2/axRfl+lLRZl1yiU4z9IoveZtNtYAV/z/0bSy0XvMLImBDoazrgX1icdslvPEZQbbMujoVCB2tMS9/NX7v4Jbbs9wHo0XoEBPS7t9TKjNS2SoWFA4FByM8v7c1ofwC/XVmDCD2iDtIU11a2dRr7blflRxwmVUjR3/vV9Vt8HUz5nB+Ut5dq1XqINBB9XTHKI5DwEPTG5xkqug5b65NeMVtxiHqoFvWTmqky4GmQyqvXMr9hjFe53YKp23RKnNTyQHaAk/yF6J07dwG/tDyamvGrvsObtERmDBP2GQPK+w4qVzxZvdOOF9uDpcVQli/sqiOhS9lDjLMSsASnIm2MAadHqND9fTbyWl8ZYwLT4YmJ+WzP/gbkdWNVZ5xA4jJ892zZTfGwWm5xv2L+bWPOClXspg3YEVN0Hld0Gf3yhCpFD1PjygNJWn+UNwUpy82LeeTQreh7Oa9P3uxzrg1SVGCTmX17Yz3aTd74UBYz+vMl1bUQrem5e4a+qI8Mf6CHh4TBQBL8ozNt76Yc+k+qKznHHXW+7kgE0lp8ywXpbR8neaEJ6YXgk2l/E8NKleQEya31DSn/Ml//1phU0v+gmaNmU2Q2j5VEJyJXCnQRb3MUnyOj8VhkFbHaxyXoHmN6Q="

addons:
  sonarcloud:
    organization: "jameshnsears-github"
    token:
      secure: "XwUFX8/52MnV+zTUszl4NPA6/8JcKiAJKS6K1xpXIBB9B/Kmp0BDOQFXEzBukMtu/HMTdJjNpqzMYtu9i9p8Wz3c0Va0/T0qVEDpAeyVhO9RCdP21U6duhAg2Ji9M9HmCo/HYQm4CMb/o2Sm93/TUJ3MXuY7f811XoVg0eQf3p5rI6cHBIKVwpU9OY+/VmeRaUkf5fjYvNWY7FFvtIY+BSsYRdIql9EaerPh2lrQCBkpPIgSYY2MwItu0sZQxCrztL/LRS/5kne5qUBukn2A1DeRyHWPBu/tgk5ORFGgEGenNjLeqwd41k4WUSB/61e3VSpvicVVx0drE398boA65/2zPEuA8HvsdtumF7GdL5ifmoA0pIn02BJ+J/ZwZ7Be+YG6UkUGjUeuUqopxmIcT547M4cdWeA0Xzj+xg7gWvYJNNLO7XqxV+9IaiFv3BNyaUR3kMj7Fn7sIFDTUFxSx3mTDZTnmiI74X+a3jiAmDl0VzVWR7JZUdCMQVZOUs+jeC8Dh5QOpg93vsQ1+iGWNLLxNRKqfEgfg1t/5Xjsa/lhcDjhZ06wO00OyDSi7iUsuETNnr4wkqThmGWSYrUMxAmzRkOg19b2zsh31FHLNMkt3iPRF+6Jh/2IMMWAzGtjQOeAloWOZNLHP8G24MR7JWaL3va9CGVr58WlqC0vvuk="

git:
  depth: false

services:
  - docker

jdk:
  - openjdk10

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

before_script:
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
  - wget https://github.com/codacy/codacy-coverage-reporter/releases/download/4.0.5/codacy-coverage-reporter-4.0.5-assembly.jar

  - wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.0.tgz
  - tar -xzf apache-jmeter-5.0.tgz

script:
  - mvn clean test
  - mvn checkstyle:check spotbugs:check pmd:pmd

  - export HEAP="-Xms1g -Xmx1g -XX:MaxMetaspaceSize=256m"
  - apache-jmeter-5.0/bin/jmeter -n -t jmeter-test-plan.jmx -l jmeter-test-plan.jtl
  - grep "Test failed" jmeter-test-plan.jtl

after_success:
  - mvn jacoco:report coveralls:report
  - java -jar codacy-coverage-reporter-4.0.5-assembly.jar report -l Java -r target/site/jacoco/jacoco.xml
  - sonar-scanner
