version: '3'

services:
  xqa-db:
    image: jameshnsears/xqa-db:latest
    container_name: xqa-db
    volumes:
      - "xqa-db:/var/lib/postgresql"
    ports:
      - "5432:5432"
    networks:
      - xqa

  xqa-message-broker:
    image: jameshnsears/xqa-message-broker:latest
    container_name: xqa-message-broker
    ports:
      - "5672:5672"
      - "8161:8161"
    volumes:
      - "xqa-message-broker:/opt/apache-activemq-5.15.7/data"
    networks:
      - xqa

  xqa-ingest-balancer:
    image: jameshnsears/xqa-ingest-balancer:latest
    container_name: xqa-ingest-balancer
    command: ["-message_broker_host", "xqa-message-broker", "-pool_size", "2", "-insert_thread_wait", "60000", "-insert_thread_secondary_wait", "1000"]
    networks:
      - xqa
    depends_on:
      - xqa-message-broker

  xqa-shard:
    image: jameshnsears/xqa-shard:latest
    command: ["-message_broker_host", "xqa-message-broker"]
    ports:
      - 1984
    networks:
      - xqa
    depends_on:
      - xqa-message-broker

volumes:
  xqa-db:
  xqa-message-broker:

networks:
  xqa:
