version: '3'

services:
  xqa-db:
    image: jameshnsears/xqa-db:latest
    volumes:
      - "xqa-db:/var/lib/postgresql"
    ports:
      - "5432:5432"
    networks:
      - xqa

  xqa-query-balancer:
    build: .
    image: "xqa-query-balancer"
    command: ["server", "xqa-query-balancer.yml"]
    depends_on:
      - xqa-db
    networks:
      - xqa

volumes:
  xqa-db:

networks:
  xqa:
