version: '3'

services:
  xqa-query-balancer:
    build: .
    image: "xqa-query-balancer"
    networks:
      - xqa
    depends_on:
      - xqa-db
      - xqa-message-broker

  xqa-db:
    image: jameshnsears/xqa-db:latest
    volumes:
      - "xqa-db:/var/lib/postgresql"
    ports:
      - "5432:5432"
    networks:
      - xqa

  xqa-message-broker:
    image: jameshnsears/xqa-message-broker:latest
    ports:
      - "5672:5672"
      - "8161:8161"
    volumes:
      - "xqa-message-broker:/opt/apache-activemq-5.15.3/data"
    networks:
      - xqa

  xqa-ingest-balancer:
    image: jameshnsears/xqa-ingest-balancer:latest
    command: ["-message_broker_host", "xqa-message-broker", "-pool_size", "2"]
    networks:
      - xqa
    depends_on:
      - xqa-message-broker

  xqa-shard:
    image: jameshnsears/xqa-shard:latest
    command: ["-message_broker_host", "xqa-message-broker"]
    networks:
      - xqa
    depends_on:
      - xqa-message-broker

volumes:
  xqa-db:
  xqa-message-broker:

networks:
  xqa:
